version: '3.8'
services:
  app:
    build: .
    image: my-node-app:latest
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DATABASE_HOST=192.168.1.201
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=walas
      - DATABASE_PASSWORD=S3cret
      - DATABASE_NAME=vending_machine
      - DATABASE_SCHEMA=vending_machine
      - JWT_EXPIRATION_TIME=24d
      - AUTH_SECRET=JWT_SECRET
    restart: unless-stopped
